site_name: Unity Cluster Documentation
plugins:
  - include-markdown
extra_css: [extra.css]
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
site_url: ""
use_directory_urls: false
theme:
  name: material
  logo: res/logo.png
copyright: "Copyright &copy;2020 UMass Amherst"
repo_url: https://github.com/UMass-RC/unity-docs
edit_uri: "edit/main/docs"
markdown_extensions:
  - admonition
  - toc:
      permalink: True
nav:
  - Home: index.md
  - Getting Started:
      - Connecting:
          - "Console - SSH": "connecting/ssh.md"
          - "Web - JupyterLab": "connecting/jupyter.md"
      - Uploading Files: "uploading-files/index.md"
      - Job Scheduling:
          - Introduction: "slurm/index.md"
          - SRUN Jobs: "slurm/srun.md"
          - SBATCH Jobs: "slurm/sbatch.md"
          - MPI: "mpi.md"
      - Software:
          - Introduction: "modules/index.md"
          - Using Modules: "modules/using.md"
  - FAQ: faq.md
  - Cluster Information:
      - Node List: "technical/nodelist.md"
      - Partition List: "technical/partitionlist.md"
      - Storage: "technical/storage.md"
      - MGHPCC Transitions: "MGHPCC/MGHPCC.md"
      - File Transfers: "transfers/transfers.md"

