site_name: Unity Cluster Documentation
plugins:
  - include-markdown
  - search
extra_css: [extra.css]
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
site_url: ""
use_directory_urls: false
theme:
  name: material
  logo: res/logo.png
copyright: "Copyright &copy;2023 UMass Amherst"
repo_url: https://github.com/UMass-RC/unity-docs
edit_uri: "edit/main/docs"
markdown_extensions:
  - admonition
  - toc:
      permalink: True
nav:
  - Home: index.md
  - Getting Started:
      - Connecting:
          - OnDemand: "connecting/ood.md"
          - "Console - SSH": "connecting/ssh.md"
          - "Web - JupyterHub": "connecting/jupyter.md"
      - Managing Files:
          - Introduction: "managing-files/intro.md"
          - OnDemand: "managing-files/ood.md"
          - "Console - SCP/Rsync": "managing-files/cli.md"
          - Globus: "managing-files/globus.md"
          - FileZilla: "managing-files/filezilla.md"
          #- HPC Workspace: "managing-files/hpc-workspace.md"
      - Job Scheduling:
          - Introduction: "slurm/index.md"
          - OnDemand: "slurm/ood.md"
          - SRUN Jobs: "slurm/srun.md"
          - SBATCH Jobs: "slurm/sbatch.md"
          - MPI: "slurm/mpi.md"
      - Software:
          - Overview: "software/index.md"
          - Environment Modules:
              - Introduction: "software/module-intro.md"
              - Basic Usage: "software/module-usage.md"
              - Hierarchy: "software/module-hierarchy.md"
          - Conda: "software/conda.md"
          - GUI Apps via OnDemand: "software/ood.md"
          - Containers: "software/apptainer.md"
          #- R: "software/R.md"
      #- JupyterHub: "jupyter/index.md"
  - FAQ: faq.md
  - Common Terms: "jargon.md"
  - Cluster Information:
      - Node List: "technical/nodelist.md"
      - Partition List: "technical/partitionlist.md"
      - Storage: "technical/storage.md"
      # - MGHPCC Transitions: "MGHPCC/MGHPCC.md"
      - File Transfers: "transfers/transfers.md"
  - Cluster Updates: "updates/index.md"
  - Shared Cluster Transition: "transition.md"
