site_name: Unity Cluster Documentation
extra_css: [extra.css]
site_url: ""
use_directory_urls: false
theme:
    name: material
    logo: res/logo.png
copyright: "Copyright &copy;2020 UMass Amherst"
markdown_extensions:
    - admonition
nav:
    - Home: index.md
    - Roadmap: "roadmap.md"
    - Cluster Information:
        - Node List: "technical/nodelist.md"
        - Partition List: "technical/partitionlist.md"
        - Storage: "technical/storage.md"
    - Connecting:
        - "Console - SSH": "connecting/ssh.md"
        - "Web - JupyterLab": "connecting/jupyter.md"
    - Job Scheduling:
        - Introduction: "slurm/index.md"
        - SRUN Jobs: "slurm/srun.md"
        - SBATCH Jobs: "slurm/sbatch.md"
    - Software:
        - Introduction: "modules/index.md"
        - Using Modules: "modules/using.md"
    - Buy-In Hardware:
        - Types of Priority: "buy-in/types.md"
        - Hardware Requirements: "buy-in/requirements.md"