site_name: Unity Cluster
extra_css: [extra.css]
theme:
    name: windmill
    highlightjs: true
extra:
    logo: 'res/logo.png'
copyright: "Copyright &copy;2020 UMass Amherst"
markdown_extensions:
    - admonition
nav:
    - Home: index.md
    - Roadmap: "roadmap.md"
    - Connecting:
        - "Console - SSH": "connecting/ssh.md"
        - "Web - JupyterLab": "connecting/jupyter.md"
    - Job Scheduling - Slurm:
        - "Introduction": "slurm/index.md"
        - "SRUN Jobs": "slurm/srun.md"
        - "SBATCH Jobs": "slurm/sbatch.md"
    - Environment Modules:
        - "Introduction": "modules/index.md"
        - "Using Modules": "modules/using.md"
    - Applications:
        - "JupyterLab":
            - "Conda Environments": "apps/jupyter/conda.md"