name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-include-markdown-plugin
      - run: wget https://github.com/UMass-RC/unity-mgmt/blob/master/README.md
      - run: mkdocs gh-deploy --force