on: push

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "UMass-RC/unity-docs"
          source_branch: "main"
          destination_repo: "UMass-RC/unity-uri-docs"
          destination_branch: "main"
