on: push

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "UMass-RC/unity-docs"
          source_branch: "master"
          destination_repo: "git@github.com:UMass-RC/unity-uri-docs.git"
          destination_branch: "main"
          destination_ssh_private_key: ${{ secrets.MIRROR_KEY }}
